inputs:
  - ./package.json
output: ./THIRD_PARTY_LICENSES
overwrite: true
eol: lf
#ci: true
#no-spinner: true

replace:
  type-fest: https://raw.githubusercontent.com/sindresorhus/type-fest/main/license-mit
